### ISSUE TITLE
Where to put tests?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl-solvers#9]
I have pushed a Newton solver in a separate branch (see #7). To this solver I have written tests, where should these be put? Where are the current tests for the other solvers, still in the `odl`-package?

**Comment by kohr-h** [comment]
Yes, they are still there. And since documentation and continuous integration seems to be quite hard to realize with sub-repositories, all the spread-out code might in fact converge to the `odl` package. We'll see.

In the meantime, put the new tests in the `test` folder, where you create a subfolder with the same name as the one in `odl_solvers`. In ODL, we chose to exactly reflect the folder structure of `odl` (the package folder) in `tests`, so you have `odl/space/ntuples.py` and `test/space/ntuples_test.py`, with this naming scheme.

**Comment by aringh** [comment]
Moved to odl, and solved by odlgroup/odl#32 and odlgroup/odl#36
